import { createServer } from 'node:http'
import { appendFile, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { spawn } from 'node:child_process'
import { createClient } from '@supabase/supabase-js'

const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL
const key=process.env.SUPABASE_SERVICE_ROLE_KEY
if(!url||!key)throw new Error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required')
const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})
const workerId=process.env.WORKER_ID||`worker-${Math.random().toString(36).slice(2,10)}`
const pollMs=Math.max(2000,Number(process.env.POLL_INTERVAL_MS||5000))
let busy=false,lastError=null,lastCompleted=null

function run(command,args){return new Promise((resolve,reject)=>{const child=spawn(command,args,{stdio:['ignore','pipe','pipe']});let stderr='';child.stderr.on('data',d=>{stderr+=d.toString();if(stderr.length>20000)stderr=stderr.slice(-20000)});child.on('error',reject);child.on('close',(code,signal)=>code===0?resolve():reject(new Error(`${command} exited ${code??signal??'unknown'}: ${stderr.slice(-3000)}`)))})}
async function patchItem(id,values){const {error}=await supabase.from('content_items').update({...values,updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error}
async function downloadSources(paths,dir){const local=[];for(let i=0;i<paths.length;i++){const {data,error}=await supabase.storage.from('content-media').download(paths[i]);if(error)throw error;const ext=path.extname(paths[i])||'.bin',target=path.join(dir,`source-${i}${ext}`);await writeFile(target,Buffer.from(await data.arrayBuffer()));local.push(target)}return local}
async function joinVideoParts(files,dir){if(files.length===1)return files[0];const target=path.join(dir,`source-combined${path.extname(files[0])||'.mp4'}`);await writeFile(target,new Uint8Array());for(const file of files)await appendFile(target,await readFile(file));return target}
async function makeSlideshow(files,settings,dir){const seconds=Math.max(2,Math.min(15,Number(settings?.perImageSec||5)));const list=[];for(const file of files){list.push(`file '${file.replaceAll("'","'\\''")}'`,`duration ${seconds}`)}list.push(`file '${files.at(-1).replaceAll("'","'\\''")}'`);const listPath=path.join(dir,'images.txt'),output=path.join(dir,'output.mp4');await writeFile(listPath,list.join('\n'));await run('ffmpeg',['-y','-filter_threads','2','-threads','2','-f','concat','-safe','0','-i',listPath,'-vf','scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2,format=yuv420p','-r','30','-c:v','libx264','-preset','veryfast','-crf','23','-movflags','+faststart',output]);return output}
async function makeVideo(input,dir){const output=path.join(dir,'output.mp4');await run('ffmpeg',['-y','-filter_threads','2','-threads','2','-i',input,'-map','0:v:0','-map','0:a?','-vf','scale=1280:1280:force_original_aspect_ratio=decrease:force_divisible_by=2,format=yuv420p','-c:v','libx264','-preset','veryfast','-crf','23','-threads','2','-c:a','aac','-b:a','128k','-movflags','+faststart',output]);return output}
async function probe(file){return new Promise((resolve,reject)=>{const child=spawn('ffprobe',['-v','error','-print_format','json','-show_format','-show_streams',file]);let out='',err='';child.stdout.on('data',d=>out+=d);child.stderr.on('data',d=>err+=d);child.on('close',code=>{if(code!==0)return reject(new Error(err));const json=JSON.parse(out),v=json.streams?.find(s=>s.codec_type==='video');resolve({durationSec:Number(json.format?.duration||0),width:Number(v?.width||0),height:Number(v?.height||0)})})})}
async function processJob(job){const dir=await mkdtemp(path.join(tmpdir(),'contentforge-'));try{await patchItem(job.content_item_id,{status:'processing',progress:10,current_step:'Downloading private media',error_message:null});const sources=await downloadSources(job.source_paths||[],dir);if(!sources.length)throw new Error('No source media found');await patchItem(job.content_item_id,{progress:30,current_step:job.kind==='slideshow'?'Building slideshow':'Optimizing video'});const videoSource=job.kind==='slideshow'?null:await joinVideoParts(sources,dir);const output=job.kind==='slideshow'?await makeSlideshow(sources,job.edit_settings,dir):await makeVideo(videoSource,dir);await patchItem(job.content_item_id,{progress:85,current_step:'Creating thumbnail'});const thumbnail=path.join(dir,'thumbnail.jpg');await run('ffmpeg',['-y','-ss','1','-i',output,'-frames:v','1','-vf','scale=640:-2','-q:v','3',thumbnail]);const prefix=`${job.user_id}/${job.workspace_id}/${job.content_item_id}`,outputPath=`${prefix}/output.mp4`,thumbnailPath=`${prefix}/thumbnail.jpg`;const [outputBytes,thumbBytes]=await Promise.all([readFile(output),readFile(thumbnail)]);const up1=await supabase.storage.from('content-media').upload(outputPath,outputBytes,{contentType:'video/mp4',upsert:true});if(up1.error)throw up1.error;const up2=await supabase.storage.from('content-media').upload(thumbnailPath,thumbBytes,{contentType:'image/jpeg',upsert:true});if(up2.error)throw up2.error;const media=await probe(output);await patchItem(job.content_item_id,{status:'ready',progress:100,current_step:'Ready to download',output_path:outputPath,thumbnail_path:thumbnailPath,metadata:{...(job.metadata||{}),...media}});const {error}=await supabase.from('processing_jobs').update({status:'completed',updated_at:new Date().toISOString()}).eq('id',job.job_id);if(error)throw error;lastCompleted={itemId:job.content_item_id,at:new Date().toISOString()}}finally{await rm(dir,{recursive:true,force:true})}}
async function failJob(job,error){const message=error instanceof Error?error.message:String(error);lastError={message,at:new Date().toISOString()};console.error('Job failed',job?.job_id,message);if(!job)return;const retry=Number(job.attempts||1)<3;await supabase.from('processing_jobs').update({status:retry?'queued':'failed',error_message:message,locked_at:null,locked_by:null,updated_at:new Date().toISOString()}).eq('id',job.job_id);await patchItem(job.content_item_id,{status:retry?'queued':'failed',progress:0,current_step:retry?'Retrying processing':null,error_message:message}).catch(()=>{})}
async function tick(){if(busy)return;busy=true;let job;try{const {data,error}=await supabase.rpc('claim_processing_job',{worker_id:workerId});if(error)throw error;job=data?.[0];if(job)await processJob(job)}catch(error){await failJob(job,error)}finally{busy=false}}

createServer((req,res)=>{res.setHeader('content-type','application/json');if(req.url==='/health'){res.end(JSON.stringify({ok:true,workerId,busy,lastCompleted,lastError}));return}res.statusCode=404;res.end(JSON.stringify({error:'Not found'}))}).listen(Number(process.env.PORT||3000),'0.0.0.0')
console.log(`ContentForge worker ${workerId} started`)
setInterval(tick,pollMs);tick()
